-- Require Lua Modules
require('settings')
require('plugins')
require('nvim-treesitter-config')
require('edenfox-feline')
require('icons')
require('gitsigns').setup()
require('nightfox')
require('mappings')
require('set-theme')
