print("Christ is King")
require('lazy-setup')
require('settings')
require('edenfox-feline')
require('icons')
require('gitsigns').setup()
require('nightfox')
require('mappings')
require('nvim-treesitter-config')
